# Generated by Django 4.2 on 2025-06-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlelisting',
            name='subtotal',
        ),
    ]
